import React, { useCallback } from 'react';
import { RunProvider, useRunState, useRunActions } from '../store/runStore';
import { DraftView } from './DraftView';
import { MapView } from './MapView';
import { CombatView } from './CombatView';
import { ShopView } from './ShopView';
import { RestSiteView } from './RestSiteView';
import { RewardScreen } from './RewardScreen';
import { RunSummary } from './RunSummary';
import { RelicBar } from './RelicBar';

interface DungeonRootProps {
  onBack?: () => void;
}

function DungeonGame({ onBack }: DungeonRootProps) {
  const state = useRunState();
  const actions = useRunActions();

  const handlePlayAgain = useCallback(() => {
    actions.startNewRun();
  }, [actions]);

  const handleMainMenu = useCallback(() => {
    if (onBack) onBack();
  }, [onBack]);

  // Start a new run if we haven't yet
  React.useEffect(() => {
    if (!state.runSeed) {
      actions.startNewRun();
    }
  }, []);

  const renderPhase = () => {
    switch (state.phase) {
      case 'DRAFT':
        return (
          <DraftView
            draftRound={state.draftRound}
            draftFaction={state.draftFaction}
            draftOptions={state.draftOptions}
            draftRelicOptions={state.draftRelicOptions}
            currentDeck={state.deck.map(c => ({
              id: c.id,
              name: c.name,
              faction: c.faction,
              cost: c.cost,
            }))}
            onSelectFaction={actions.selectDraftFaction}
            onPickCard={actions.pickDraftCard}
            onPickRelic={actions.pickStartingRelic}
          />
        );

      case 'MAP':
        return (
          <div style={styles.mapScreen}>
            <div style={styles.mapTopBar}>
              <RelicBar relics={state.relics} />
              <div style={styles.mapInfo}>
                <span style={styles.goldDisplay}>💰 {state.gold}</span>
                <span style={styles.hpDisplay}>❤️ {state.heroHealth}/{state.maxHeroHealth}</span>
                <span style={styles.deckCount}>📚 {state.deck.length} cards</span>
              </div>
            </div>
            <MapView
              map={state.map}
              currentNodeId={state.currentNodeId}
              onSelectNode={actions.moveToNode}
              act={state.act}
            />
            {onBack && (
              <button onClick={onBack} style={styles.backButton}>
                ← Abandon Run
              </button>
            )}
          </div>
        );

      case 'COMBAT':
        return (
          <CombatView
            state={state}
            onPlayCard={actions.playCard}
            onAttackWithMinion={actions.attackWithMinion}
            onEndTurn={actions.endPlayerTurn}
            onSelectMinion={actions.selectMinion}
            onSelectCard={actions.selectCard}
            onExecuteEnemyTurn={actions.executeEnemyTurn}
          />
        );

      case 'SHOP':
        return (
          <ShopView
            items={[]} // shop items generated by store
            gold={state.gold}
            deck={state.deck}
            onBuyCard={actions.buyCard}
            onBuyRelic={actions.buyRelic}
            onRemoveCard={actions.removeCard}
            onUpgradeCard={(id) => actions.upgradeCard(id)}
            onLeave={actions.returnToMap}
          />
        );

      case 'REST':
        return (
          <RestSiteView
            heroHealth={state.heroHealth}
            maxHeroHealth={state.maxHeroHealth}
            deck={state.deck}
            onHeal={actions.healAtRest}
            onUpgrade={(instanceId) => actions.upgradeCard(instanceId)}
            onLeave={actions.returnToMap}
          />
        );

      case 'REWARD':
        if (state.reward) {
          return (
            <RewardScreen
              reward={state.reward}
              onPickCard={actions.pickRewardCard}
              onPickRelic={actions.pickRewardRelic}
              onSkip={actions.skipReward}
            />
          );
        }
        // Fallback: return to map
        actions.returnToMap();
        return null;

      case 'ACT_TRANSITION':
        return (
          <div style={styles.actTransition}>
            <div style={styles.actTransitionContent}>
              <div style={styles.actTransitionTitle}>
                ACT {state.act}
              </div>
              <div style={styles.actTransitionSubtitle}>
                {state.act === 1 && 'The Outer Forge'}
                {state.act === 2 && 'The Void Depths'}
                {state.act === 3 && 'The Star Core'}
              </div>
              <button onClick={actions.nextAct} style={styles.enterActButton}>
                ENTER ACT {state.act}
              </button>
            </div>
          </div>
        );

      case 'VICTORY':
        return (
          <RunSummary
            victory={true}
            stats={state.stats}
            deck={state.deck}
            relics={state.relics}
            act={state.act}
            onPlayAgain={handlePlayAgain}
            onMainMenu={handleMainMenu}
          />
        );

      case 'DEATH':
        return (
          <RunSummary
            victory={false}
            stats={state.stats}
            deck={state.deck}
            relics={state.relics}
            act={state.act}
            onPlayAgain={handlePlayAgain}
            onMainMenu={handleMainMenu}
          />
        );

      default:
        return (
          <div style={styles.loading}>Loading...</div>
        );
    }
  };

  return (
    <div style={styles.root}>
      {renderPhase()}
    </div>
  );
}

export function DungeonRoot({ onBack }: DungeonRootProps) {
  return (
    <RunProvider>
      <DungeonGame onBack={onBack} />
    </RunProvider>
  );
}

const styles: Record<string, React.CSSProperties> = {
  root: {
    width: '100%',
    height: '100vh',
    overflow: 'hidden',
    background: '#0a0a1a',
    fontFamily: "'Segoe UI', system-ui, sans-serif",
  },
  mapScreen: {
    width: '100%',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: 'linear-gradient(180deg, #0a0a1a 0%, #1a1a2e 100%)',
  },
  mapTopBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 16px',
    borderBottom: '1px solid rgba(255,255,255,0.1)',
    flexShrink: 0,
  },
  mapInfo: {
    display: 'flex',
    gap: '16px',
    alignItems: 'center',
    color: '#fff',
    fontSize: '14px',
  },
  goldDisplay: {
    color: '#ffd700',
    fontWeight: 'bold',
  },
  hpDisplay: {
    color: '#ef4444',
    fontWeight: 'bold',
  },
  deckCount: {
    color: '#60a5fa',
  },
  backButton: {
    position: 'absolute',
    bottom: '16px',
    left: '16px',
    padding: '8px 16px',
    background: 'rgba(255,255,255,0.1)',
    border: '1px solid rgba(255,255,255,0.2)',
    color: '#aaa',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  actTransition: {
    width: '100%',
    height: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background: 'radial-gradient(ellipse at center, #1a1a2e 0%, #000 100%)',
  },
  actTransitionContent: {
    textAlign: 'center',
    color: '#fff',
  },
  actTransitionTitle: {
    fontSize: '72px',
    fontWeight: 'bold',
    letterSpacing: '8px',
    color: '#ffd700',
    textShadow: '0 0 40px rgba(255,215,0,0.5)',
    marginBottom: '16px',
  },
  actTransitionSubtitle: {
    fontSize: '24px',
    color: '#aaa',
    fontStyle: 'italic',
    marginBottom: '48px',
  },
  enterActButton: {
    padding: '16px 48px',
    fontSize: '20px',
    fontWeight: 'bold',
    background: 'linear-gradient(135deg, #ffd700, #b8860b)',
    color: '#000',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
    letterSpacing: '3px',
    boxShadow: '0 0 30px rgba(255,215,0,0.4)',
  },
  loading: {
    width: '100%',
    height: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#666',
    fontSize: '20px',
  },
};
