// Auto-generated from docs/roguelite/factions/cogsmiths-cards.xlsx.
// Do not hand-edit — re-run the generator (docs/roguelite/01-card-content-notes.md).

import type { Card } from '../types';

export const COGSMITHS_BASE_CARDS: Card[] = [
  {
    id: 'C-001',
    name: 'Rivet Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 7 damage.',
    archetype: 'Basic',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'C-001-EVOLVED',
      evolvedDescription: 'Deal 10 damage.',
    },
  },
  {
    id: 'C-002',
    name: 'Plate Shield',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 6 Block.',
    archetype: 'Basic',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'C-002-EVOLVED',
      evolvedDescription: 'Gain 8 Block.',
    },
  },
  {
    id: 'C-003',
    name: 'Tinker',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Draw 1 card. The next Augment you play this turn costs 0.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-003-EVOLVED',
      evolvedDescription: 'Draw 1 card. The next 2 Augments you play this turn cost 0.',
    },
  },
  {
    id: 'C-004',
    name: 'Socket Wrench',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 5 damage + 3 damage per Augment on this card.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 2,
      conditionText: 'Played with 2 Augments 5 times',
      evolvesTo: 'C-004-EVOLVED',
      evolvedDescription: 'Deal 6 damage + 4 damage per Augment on this card.',
    },
  },
  {
    id: 'C-005',
    name: 'Hammer Blow',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 9 damage. Exhaust.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'C-005-EVOLVED',
      evolvedDescription: 'Deal 12 damage. Exhaust.',
    },
  },
  {
    id: 'C-006',
    name: 'Bolt Thrower',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 3 damage twice.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'C-006-EVOLVED',
      evolvedDescription: 'Deal 4 damage twice.',
    },
  },
  {
    id: 'C-007',
    name: 'Gear Shift',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 4 Block. Draw 1 card.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'C-007-EVOLVED',
      evolvedDescription: 'Gain 5 Block. Draw 2 cards.',
    },
  },
  {
    id: 'C-008',
    name: 'Pneumatic Jab',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 13 damage.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'C-008-EVOLVED',
      evolvedDescription: 'Deal 16 damage.',
    },
  },
  {
    id: 'C-009',
    name: 'Crosswire',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Your next Attack this turn costs 0.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-009-EVOLVED',
      evolvedDescription: 'Your next 2 Attacks this turn cost 0.',
    },
  },
  {
    id: 'C-010',
    name: 'Servo Shield',
    rarity: 'Common',
    type: 'Power',
    cost: 1,
    description: 'At start of each turn, gain 3 Block.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 8,
      conditionText: 'Triggered 8 times',
      evolvesTo: 'C-010-EVOLVED',
      evolvedDescription: 'At start of each turn, gain 4 Block.',
    },
  },
  {
    id: 'C-011',
    name: 'Deploy Drone',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Summon a Drone (5 HP, deals 3 damage at turn end, lasts 3 turns).',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-011-EVOLVED',
      evolvedDescription: 'Summon a Scout (7 HP, deals 4 damage at turn end, lasts 4 turns).',
    },
  },
  {
    id: 'C-012',
    name: 'Toolkit',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Add a random Augment to your hand.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-012-EVOLVED',
      evolvedDescription: 'Add 2 random Augments to your hand.',
    },
  },
  {
    id: 'C-013',
    name: 'Overdrive',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 1 Energy. Draw 2 cards. Take 3 damage.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-013-EVOLVED',
      evolvedDescription: 'Gain 1 Energy. Draw 2 cards. Take 2 damage.',
    },
  },
  {
    id: 'C-014',
    name: 'Augment: Edge',
    rarity: 'Common',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card deals +3 damage. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'edge',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 5,
      conditionText: 'Attached 5 times',
      evolvesTo: 'C-014-EVOLVED',
      evolvedDescription: 'Attach to a card in hand: card deals +5 damage. Exhaust.',
    },
  },
  {
    id: 'C-015',
    name: 'Augment: Plate',
    rarity: 'Common',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card grants +3 Block. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'plate',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 5,
      conditionText: 'Attached 5 times',
      evolvesTo: 'C-015-EVOLVED',
      evolvedDescription: 'Attach to a card in hand: card grants +5 Block. Exhaust.',
    },
  },
  {
    id: 'C-016',
    name: 'Augment: Jolt',
    rarity: 'Common',
    type: 'Augment',
    cost: 1,
    description: 'Attach to an Attack in hand: attack applies Weak 1. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'jolt',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 5,
      conditionText: 'Attached 5 times',
      evolvesTo: 'C-016-EVOLVED',
      evolvedDescription: 'Attach to an Attack in hand: attack applies Weak 2. Exhaust.',
    },
  },
  {
    id: 'C-017',
    name: 'Heavy Wrench',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 16 damage.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'C-017-EVOLVED',
      evolvedDescription: 'Deal 20 damage.',
    },
  },
  {
    id: 'C-018',
    name: 'Shock Coil',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 5 damage. Apply Weak 2.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'C-018-EVOLVED',
      evolvedDescription: 'Deal 7 damage. Apply Weak 3.',
    },
  },
  {
    id: 'C-019',
    name: 'Deploy Sentry',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Summon a Sentry (8 HP, deals 6 damage at turn end, lasts 4 turns).',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-019-EVOLVED',
      evolvedDescription: 'Summon a Vanguard (12 HP, deals 8 damage at turn end, lasts 4 turns).',
    },
  },
  {
    id: 'C-020',
    name: 'Full Plate',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Gain 14 Block.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'C-020-EVOLVED',
      evolvedDescription: 'Gain 18 Block.',
    },
  },
  {
    id: 'C-021',
    name: 'Modular Strike',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 6 damage + 4 damage per Augment on any card in your deck.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 4,
      conditionText: 'Played with 4+ total augments in deck 5 times',
      evolvesTo: 'C-021-EVOLVED',
      evolvedDescription: 'Deal 8 damage + 5 damage per Augment on any card in your deck.',
    },
  },
  {
    id: 'C-022',
    name: 'Automate',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Copy an Augment from a card in your deck and add it to your hand.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'C-022-EVOLVED',
      evolvedDescription: 'Copy 2 Augments from cards in your deck and add them to your hand.',
    },
  },
  {
    id: 'C-023',
    name: 'Precision Bore',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 10 damage that ignores Block.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-023-EVOLVED',
      evolvedDescription: 'Deal 14 damage that ignores Block.',
    },
  },
  {
    id: 'C-024',
    name: 'Whirring Blades',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 4 damage 3 times.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'C-024-EVOLVED',
      evolvedDescription: 'Deal 5 damage 3 times.',
    },
  },
  {
    id: 'C-025',
    name: 'Repair Nanites',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Heal 8 HP.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'C-025-EVOLVED',
      evolvedDescription: 'Heal 12 HP.',
    },
  },
  {
    id: 'C-026',
    name: 'Assembly Line',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'At end of turn, if you played 3 or more cards this turn, draw 1 card.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'C-026-EVOLVED',
      evolvedDescription: 'At end of turn, if you played 3 or more cards this turn, draw 2 cards.',
    },
  },
  {
    id: 'C-027',
    name: 'Augment: Core',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card draws a card when played. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'core',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 5,
      conditionText: 'Attached 5 times',
      evolvesTo: 'C-027-EVOLVED',
      evolvedDescription: 'Attach to a card in hand: card draws 2 cards when played. Exhaust.',
    },
  },
  {
    id: 'C-028',
    name: 'Augment: Gyro',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card costs 1 less Energy (min 0). Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'gyro',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 4,
      conditionText: 'Attached 4 times',
      evolvesTo: 'C-028-EVOLVED',
      evolvedDescription: 'Attach to a card in hand: card costs 2 less Energy (min 0). Exhaust.',
    },
  },
  {
    id: 'C-029',
    name: 'Augment: Bulwark',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a Skill in hand: Block from this card retains for 1 turn. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'bulwark',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 3,
      conditionText: 'Attached 3 times',
      evolvesTo: 'C-029-EVOLVED',
      evolvedDescription: 'Attach to a Skill in hand: Block from this card retains for 1 turn and gains +2. Exhaust.',
    },
  },
  {
    id: 'C-030',
    name: 'Augment: Amp',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to an Attack in hand: once per combat, this card deals double damage. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'amp',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 3,
      conditionText: 'Attached 3 times',
      evolvesTo: 'C-030-EVOLVED',
      evolvedDescription: 'Attach to an Attack in hand: twice per combat, this card deals double damage. Exhaust.',
    },
  },
  {
    id: 'C-031',
    name: 'Mecha Form',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Gain 3 Strength. All Augment cards cost 0 for the rest of this combat.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 5,
      conditionText: 'Survived 5 combats',
      evolvesTo: 'C-031-EVOLVED',
      evolvedDescription: 'Gain 4 Strength. All Augment cards cost 0 for the rest of this combat.',
    },
  },
  {
    id: 'C-032',
    name: 'Warforge',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'All Augment effects are doubled.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'C-032-EVOLVED',
      evolvedDescription: 'All Augment effects are tripled.',
    },
  },
  {
    id: 'C-033',
    name: 'Colossus Strike',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 30 damage + 25 damage per Augment on this card.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 2,
      conditionText: 'Played with 2 Augments 3 times',
      evolvesTo: 'C-033-EVOLVED',
      evolvedDescription: 'Deal 35 damage + 30 damage per Augment on this card.',
    },
  },
  {
    id: 'C-034',
    name: 'Deploy Titan',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Summon a Titan (25 HP, takes 2 actions per turn dealing 10 damage each).',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 3,
      conditionText: 'Played 3 times',
      evolvesTo: 'C-034-EVOLVED',
      evolvedDescription: 'Summon a Warmind (35 HP, takes 2 actions per turn dealing 14 damage each).',
    },
  },
  {
    id: 'C-035',
    name: 'Iron Commandment',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'The first Attack you play each turn is treated as having an extra Edge and Jolt Augment.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'C-035-EVOLVED',
      evolvedDescription: 'The first 2 Attacks you play each turn are treated as having an extra Edge and Jolt Augment.',
    },
  },
  {
    id: 'C-036',
    name: 'Overclocked Core',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At combat start, gain 1 extra Energy this turn. Take 2 damage at end of each turn.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 5,
      conditionText: 'Survived 5 combats',
      evolvesTo: 'C-036-EVOLVED',
      evolvedDescription: 'At combat start, gain 2 extra Energy this turn. Take 2 damage at end of each turn.',
    },
  },
  {
    id: 'C-037',
    name: 'Machine God',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'All Drones, Sentries, and Titans you summon have +5 HP and +2 damage.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 8,
      conditionText: 'Triggered 8 times',
      evolvesTo: 'C-037-EVOLVED',
      evolvedDescription: 'All Drones, Sentries, and Titans you summon have +8 HP and +3 damage.',
    },
  },
  {
    id: 'C-038',
    name: 'Augment: Exotic Core',
    rarity: 'Rare',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card costs 0 and does not exhaust for the rest of this combat. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'exotic_core',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 2,
      conditionText: 'Attached 2 times',
      evolvesTo: 'C-038-EVOLVED',
      evolvedDescription: 'Attach to a card in hand: card costs 0, does not exhaust, and duplicates on play for the rest of this combat. Exhaust.',
    },
  },
  {
    id: 'C-039',
    name: 'Augment: Inverter',
    rarity: 'Rare',
    type: 'Augment',
    cost: 2,
    description: 'Attach to a card in hand: attack hits all enemies / skill applies to all allies. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    augmentCategory: 'inverter',
    evolutionRule: {
      triggerType: 'attach_count',
      threshold: 2,
      conditionText: 'Attached 2 times',
      evolvesTo: 'C-039-EVOLVED',
      evolvedDescription: 'Attach to a card in hand: attack hits all enemies / skill applies to all allies. Effect is doubled. Exhaust.',
    },
  },
  {
    id: 'C-040',
    name: 'Reinforce Protocol',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Attach a random Augment to every card in your hand. Exhaust.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 2,
      conditionText: 'Played 2 times',
      evolvesTo: 'C-040-EVOLVED',
      evolvedDescription: 'Attach 2 random Augments to every card in your hand. Exhaust.',
    },
  },
];

export const COGSMITHS_EVOLVED_CARDS: Card[] = [
  {
    id: 'C-001-EVOLVED',
    name: 'Piston Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 10 damage.',
    archetype: 'Basic',
    factionId: 'Cogsmiths',
    basedOn: 'C-001',
  },
  {
    id: 'C-002-EVOLVED',
    name: 'Reinforced Plate',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 8 Block.',
    archetype: 'Basic',
    factionId: 'Cogsmiths',
    basedOn: 'C-002',
  },
  {
    id: 'C-003-EVOLVED',
    name: 'Jury-Rig',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Draw 1 card. The next 2 Augments you play this turn cost 0.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-003',
  },
  {
    id: 'C-004-EVOLVED',
    name: 'Torque Wrench',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 6 damage + 4 damage per Augment on this card.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-004',
  },
  {
    id: 'C-005-EVOLVED',
    name: 'Sledge Hammer',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 12 damage. Exhaust.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-005',
  },
  {
    id: 'C-006-EVOLVED',
    name: 'Nail Gun',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 4 damage twice.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-006',
  },
  {
    id: 'C-007-EVOLVED',
    name: 'Shifter',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 5 Block. Draw 2 cards.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-007',
  },
  {
    id: 'C-008-EVOLVED',
    name: 'Hydraulic Jab',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 16 damage.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-008',
  },
  {
    id: 'C-009-EVOLVED',
    name: 'Short Circuit',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Your next 2 Attacks this turn cost 0.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-009',
  },
  {
    id: 'C-010-EVOLVED',
    name: 'Servo Bulwark',
    rarity: 'Common',
    type: 'Power',
    cost: 1,
    description: 'At start of each turn, gain 4 Block.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-010',
  },
  {
    id: 'C-011-EVOLVED',
    name: 'Deploy Scout',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Summon a Scout (7 HP, deals 4 damage at turn end, lasts 4 turns).',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-011',
  },
  {
    id: 'C-012-EVOLVED',
    name: 'Master Toolkit',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Add 2 random Augments to your hand.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-012',
  },
  {
    id: 'C-013-EVOLVED',
    name: 'Redline',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 1 Energy. Draw 2 cards. Take 2 damage.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-013',
  },
  {
    id: 'C-014-EVOLVED',
    name: 'Augment: Razor Edge',
    rarity: 'Common',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card deals +5 damage. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-014',
    augmentCategory: 'edge',
  },
  {
    id: 'C-015-EVOLVED',
    name: 'Augment: Kite Plate',
    rarity: 'Common',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card grants +5 Block. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-015',
    augmentCategory: 'plate',
  },
  {
    id: 'C-016-EVOLVED',
    name: 'Augment: Arc Jolt',
    rarity: 'Common',
    type: 'Augment',
    cost: 1,
    description: 'Attach to an Attack in hand: attack applies Weak 2. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-016',
    augmentCategory: 'jolt',
  },
  {
    id: 'C-017-EVOLVED',
    name: 'Crushing Wrench',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 20 damage.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-017',
  },
  {
    id: 'C-018-EVOLVED',
    name: 'Induction Coil',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 7 damage. Apply Weak 3.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-018',
  },
  {
    id: 'C-019-EVOLVED',
    name: 'Deploy Vanguard',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Summon a Vanguard (12 HP, deals 8 damage at turn end, lasts 4 turns).',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-019',
  },
  {
    id: 'C-020-EVOLVED',
    name: 'Siege Plate',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Gain 18 Block.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-020',
  },
  {
    id: 'C-021-EVOLVED',
    name: 'Lattice Strike',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 8 damage + 5 damage per Augment on any card in your deck.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-021',
  },
  {
    id: 'C-022-EVOLVED',
    name: 'Mass Produce',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Copy 2 Augments from cards in your deck and add them to your hand.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-022',
  },
  {
    id: 'C-023-EVOLVED',
    name: 'Diamond Bore',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 14 damage that ignores Block.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-023',
  },
  {
    id: 'C-024-EVOLVED',
    name: 'Buzzsaw',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 5 damage 3 times.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-024',
  },
  {
    id: 'C-025-EVOLVED',
    name: 'Reconstruct',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Heal 12 HP.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-025',
  },
  {
    id: 'C-026-EVOLVED',
    name: 'Production Line',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'At end of turn, if you played 3 or more cards this turn, draw 2 cards.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-026',
  },
  {
    id: 'C-027-EVOLVED',
    name: 'Augment: Neural Core',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card draws 2 cards when played. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-027',
    augmentCategory: 'core',
  },
  {
    id: 'C-028-EVOLVED',
    name: 'Augment: Quantum Gyro',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card costs 2 less Energy (min 0). Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-028',
    augmentCategory: 'gyro',
  },
  {
    id: 'C-029-EVOLVED',
    name: 'Augment: Aegis Bulwark',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a Skill in hand: Block from this card retains for 1 turn and gains +2. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-029',
    augmentCategory: 'bulwark',
  },
  {
    id: 'C-030-EVOLVED',
    name: 'Augment: Ultra Amp',
    rarity: 'Uncommon',
    type: 'Augment',
    cost: 1,
    description: 'Attach to an Attack in hand: twice per combat, this card deals double damage. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-030',
    augmentCategory: 'amp',
  },
  {
    id: 'C-031-EVOLVED',
    name: 'Titan Form',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Gain 4 Strength. All Augment cards cost 0 for the rest of this combat.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-031',
  },
  {
    id: 'C-032-EVOLVED',
    name: 'Deepforge',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'All Augment effects are tripled.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-032',
  },
  {
    id: 'C-033-EVOLVED',
    name: 'Titanforged Strike',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 35 damage + 30 damage per Augment on this card.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-033',
  },
  {
    id: 'C-034-EVOLVED',
    name: 'Deploy Warmind',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Summon a Warmind (35 HP, takes 2 actions per turn dealing 14 damage each).',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-034',
  },
  {
    id: 'C-035-EVOLVED',
    name: 'Steel Commandment',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'The first 2 Attacks you play each turn are treated as having an extra Edge and Jolt Augment.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-035',
  },
  {
    id: 'C-036-EVOLVED',
    name: 'Singularity Core',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At combat start, gain 2 extra Energy this turn. Take 2 damage at end of each turn.',
    archetype: 'Overclock Combo',
    factionId: 'Cogsmiths',
    basedOn: 'C-036',
  },
  {
    id: 'C-037-EVOLVED',
    name: 'War God',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'All Drones, Sentries, and Titans you summon have +8 HP and +3 damage.',
    archetype: 'Heavy Plating',
    factionId: 'Cogsmiths',
    basedOn: 'C-037',
  },
  {
    id: 'C-038-EVOLVED',
    name: 'Augment: Singularity Core',
    rarity: 'Rare',
    type: 'Augment',
    cost: 1,
    description: 'Attach to a card in hand: card costs 0, does not exhaust, and duplicates on play for the rest of this combat. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-038',
    augmentCategory: 'exotic_core',
  },
  {
    id: 'C-039-EVOLVED',
    name: 'Augment: Paradox Inverter',
    rarity: 'Rare',
    type: 'Augment',
    cost: 2,
    description: 'Attach to a card in hand: attack hits all enemies / skill applies to all allies. Effect is doubled. Exhaust.',
    archetype: 'Augment',
    factionId: 'Cogsmiths',
    basedOn: 'C-039',
    augmentCategory: 'inverter',
  },
  {
    id: 'C-040-EVOLVED',
    name: 'War Protocol',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Attach 2 random Augments to every card in your hand. Exhaust.',
    archetype: 'Siege Engine',
    factionId: 'Cogsmiths',
    basedOn: 'C-040',
  },
];

export const COGSMITHS_CARDS: Card[] = [
  ...COGSMITHS_BASE_CARDS,
  ...COGSMITHS_EVOLVED_CARDS,
];
