// Auto-generated from docs/roguelite/factions/luminar-cards.xlsx.
// Do not hand-edit — re-run the generator (docs/roguelite/01-card-content-notes.md).

import type { Card } from '../types';

export const LUMINAR_BASE_CARDS: Card[] = [
  {
    id: 'L-001',
    name: 'Light Jab',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 6 damage.',
    archetype: 'Basic',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'L-001-EVOLVED',
      evolvedDescription: 'Deal 9 damage.',
    },
  },
  {
    id: 'L-002',
    name: 'Glow Ward',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 5 Block.',
    archetype: 'Basic',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'L-002-EVOLVED',
      evolvedDescription: 'Gain 7 Block. Gain 1 Lumen on a Channel card in hand.',
    },
  },
  {
    id: 'L-003',
    name: 'Meditate',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Draw 2 cards. Gain 1 Lumen on each Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'L-003-EVOLVED',
      evolvedDescription: 'Draw 2 cards. Gain 2 Lumens on each Channel card in hand.',
    },
  },
  {
    id: 'L-004',
    name: 'Prism Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Channel. Deal 6 damage. Release: +2 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'release_with_condition',
      threshold: 5,
      conditionText: 'Released at 5 Lumens',
      evolvesTo: 'L-004-EVOLVED',
      evolvedDescription: 'Channel. Deal 8 damage. Release: +3 damage per Lumen.',
    },
  },
  {
    id: 'L-005',
    name: 'Radiance',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 2 Lumens on the leftmost Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'L-005-EVOLVED',
      evolvedDescription: 'Gain 2 Lumens on every Channel card in hand.',
    },
  },
  {
    id: 'L-006',
    name: 'Halo Ward',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Channel. Gain 6 Block. Release: +2 Block per Lumen.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'release_with_condition',
      threshold: 4,
      conditionText: 'Released at 4+ Lumens',
      evolvesTo: 'L-006-EVOLVED',
      evolvedDescription: 'Channel. Gain 8 Block. Release: +3 Block per Lumen.',
    },
  },
  {
    id: 'L-007',
    name: 'Beam',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 4 damage to all enemies.',
    archetype: 'Support',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'L-007-EVOLVED',
      evolvedDescription: 'Deal 5 damage to all enemies.',
    },
  },
  {
    id: 'L-008',
    name: 'Chant',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'The next Channel card you play this turn is treated as having +2 Lumens.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'L-008-EVOLVED',
      evolvedDescription: 'The next Channel card you play this turn is treated as having +3 Lumens.',
    },
  },
  {
    id: 'L-009',
    name: 'Sunrise',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 1 Lumen on a Channel card in hand. Draw 1 card.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'L-009-EVOLVED',
      evolvedDescription: 'Gain 2 Lumens on a Channel card in hand. Draw 1 card.',
    },
  },
  {
    id: 'L-010',
    name: 'Hymn',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Heal 3 HP. Gain 1 Lumen on a Channel card in hand.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'L-010-EVOLVED',
      evolvedDescription: 'Heal 5 HP. Gain 1 Lumen on every Channel card in hand.',
    },
  },
  {
    id: 'L-011',
    name: 'Gleam',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Channel. Deal 8 damage. Release: +4 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'L-011-EVOLVED',
      evolvedDescription: 'Channel. Deal 10 damage. Release: +5 damage per Lumen.',
    },
  },
  {
    id: 'L-012',
    name: 'Steady Light',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Channel. Gain 4 Block. Retain.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'hold_turns',
      threshold: 5,
      conditionText: 'Held 5 turns',
      evolvesTo: 'L-012-EVOLVED',
      evolvedDescription: 'Channel. Gain 5 Block. Retain. Gain 1 Lumen when retained.',
    },
  },
  {
    id: 'L-013',
    name: 'Harmonize',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Transfer Lumens freely between Channel cards in hand.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'L-013-EVOLVED',
      evolvedDescription: 'Transfer Lumens freely between Channel cards. Each transfer adds +1 Lumen.',
    },
  },
  {
    id: 'L-014',
    name: 'Searing Ray',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 12 damage. +2 damage for each Channel card in hand.',
    archetype: 'Support',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'L-014-EVOLVED',
      evolvedDescription: 'Deal 14 damage. +3 damage for each Channel card in hand.',
    },
  },
  {
    id: 'L-015',
    name: 'Ward of Dawn',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 8 Block.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'L-015-EVOLVED',
      evolvedDescription: 'Gain 10 Block. Draw 1 card if at full HP.',
    },
  },
  {
    id: 'L-016',
    name: 'Inner Peace',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'End turn. Draw 2 cards next turn. Gain 1 Lumen on every Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 3,
      conditionText: 'Played 3 times',
      evolvesTo: 'L-016-EVOLVED',
      evolvedDescription: 'End turn. Draw 3 cards next turn. Gain 2 Lumens on every Channel card in hand.',
    },
  },
  {
    id: 'L-017',
    name: 'Sunbeam',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Channel. Deal 10 damage. Release: +3 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'release_count',
      threshold: 5,
      conditionText: 'Released 5 times',
      evolvesTo: 'L-017-EVOLVED',
      evolvedDescription: 'Channel. Deal 12 damage. Release: +4 damage per Lumen.',
    },
  },
  {
    id: 'L-018',
    name: 'Aurora',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Channel. Apply Vulnerable 2 to all enemies. Release: +1 Vulnerable per Lumen.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'L-018-EVOLVED',
      evolvedDescription: 'Channel. Apply Vulnerable 2 and Weak 1 to all. Release: +1 each per Lumen.',
    },
  },
  {
    id: 'L-019',
    name: 'Mantra',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 1,
    description: 'The first card you play each turn gains Channel and 1 Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'L-019-EVOLVED',
      evolvedDescription: 'The first card you play each turn gains Channel and 2 Lumens.',
    },
  },
  {
    id: 'L-020',
    name: 'Focus',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Gain 3 Lumens distributed freely across Channel cards in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'L-020-EVOLVED',
      evolvedDescription: 'Gain 5 Lumens distributed freely across Channel cards in hand.',
    },
  },
  {
    id: 'L-021',
    name: 'Solar Bolt',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 14 damage. Exhaust.',
    archetype: 'Support',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'L-021-EVOLVED',
      evolvedDescription: 'Deal 18 damage. Exhaust.',
    },
  },
  {
    id: 'L-022',
    name: 'Halo',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'At end of turn, gain Block equal to total Lumens across all Channel cards in hand.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 15,
      conditionText: 'Triggered 15 times',
      evolvesTo: 'L-022-EVOLVED',
      evolvedDescription: 'At end of turn, gain double Block from total Lumens in hand.',
    },
  },
  {
    id: 'L-023',
    name: 'Blinding Flash',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Apply Weak 2 and Vulnerable 2 to all enemies. Consume 1 Lumen from each Channel card.',
    archetype: 'Support',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 3,
      conditionText: 'Played 3 times',
      evolvesTo: 'L-023-EVOLVED',
      evolvedDescription: 'Apply Weak 3 and Vulnerable 3 to all enemies. No Lumen cost.',
    },
  },
  {
    id: 'L-024',
    name: 'Sacred Geometry',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'The next Release effect this turn triggers twice.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 3,
      conditionText: 'Played 3 times',
      evolvesTo: 'L-024-EVOLVED',
      evolvedDescription: 'The next Release effect this turn triggers three times.',
    },
  },
  {
    id: 'L-025',
    name: 'Astral Step',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 0,
    description: 'Discard your hand, draw 3 cards. Drawn Channel cards gain 1 Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'L-025-EVOLVED',
      evolvedDescription: 'Discard your hand, draw 4 cards. Drawn Channel cards gain 2 Lumens.',
    },
  },
  {
    id: 'L-026',
    name: 'Starfall',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Channel. Deal 5 damage 3 times. Release: +2 damage per hit per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'release_with_condition',
      threshold: 3,
      conditionText: 'Released at 3+ Lumens',
      evolvesTo: 'L-026-EVOLVED',
      evolvedDescription: 'Channel. Deal 6 damage 3 times. Release: +3 damage per hit per Lumen.',
    },
  },
  {
    id: 'L-027',
    name: 'Enduring Light',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Channel cards automatically Retain.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 5,
      conditionText: 'Survived 5 combats',
      evolvesTo: 'L-027-EVOLVED',
      evolvedDescription: 'Channel cards automatically Retain. +1 Lumen each time they retain.',
    },
  },
  {
    id: 'L-028',
    name: 'Focused Beam',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Channel. Deal 20 damage. Release: Apply Weak 1 per Lumen.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'release_with_condition',
      threshold: 5,
      conditionText: 'Released at 5 Lumens',
      evolvesTo: 'L-028-EVOLVED',
      evolvedDescription: 'Channel. Deal 25 damage. Release: Apply Weak 1 per Lumen.',
    },
  },
  {
    id: 'L-029',
    name: 'Moonlit Guard',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Gain 16 Block. Gain 1 Lumen on every Channel card in hand.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'L-029-EVOLVED',
      evolvedDescription: 'Gain 20 Block. Gain 2 Lumens on every Channel card in hand.',
    },
  },
  {
    id: 'L-030',
    name: 'Wisdom',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Draw cards equal to total Lumens on Channel cards in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'draw_via_this',
      threshold: 10,
      conditionText: 'Drew 10 cards via this effect',
      evolvesTo: 'L-030-EVOLVED',
      evolvedDescription: 'Draw cards equal to total Lumens + 1 on Channel cards in hand.',
    },
  },
  {
    id: 'L-031',
    name: 'Supernova',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Channel. Deal 20 damage to all enemies. Release: +10 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'release_with_condition',
      threshold: 5,
      conditionText: 'Released at 5 Lumens',
      evolvesTo: 'L-031-EVOLVED',
      evolvedDescription: 'Channel. Deal 25 damage to all enemies. Release: +12 damage per Lumen.',
    },
  },
  {
    id: 'L-032',
    name: 'Everlight',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At turn start, gain 1 Lumen on every Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'L-032-EVOLVED',
      evolvedDescription: 'At turn start, gain 2 Lumens on every Channel card in hand.',
    },
  },
  {
    id: 'L-033',
    name: 'Transcendence',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'Choose a Channel card in your draw pile. Play it immediately, ignoring cost.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 3,
      conditionText: 'Played 3 times',
      evolvesTo: 'L-033-EVOLVED',
      evolvedDescription: 'Choose 2 Channel cards in your draw pile. Play them immediately, ignoring cost.',
    },
  },
  {
    id: 'L-034',
    name: 'Gravitas',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'All Release effects are doubled.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 15,
      conditionText: 'Triggered 15 times',
      evolvesTo: 'L-034-EVOLVED',
      evolvedDescription: 'All Release effects are tripled.',
    },
  },
  {
    id: 'L-035',
    name: 'Stellar Body',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'The first attack that would damage you each turn is reduced to 0.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'survived_attacks',
      threshold: 10,
      conditionText: 'Survived 10 attacks',
      evolvesTo: 'L-035-EVOLVED',
      evolvedDescription: 'The first attack that would damage you each turn is reduced to 0. Gain 2 Lumens when this triggers.',
    },
  },
  {
    id: 'L-036',
    name: 'Illumination',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'Reveal all enemy intents for the rest of combat. Apply Vulnerable 3 to all.',
    archetype: 'Support',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 3,
      conditionText: 'Played 3 times',
      evolvesTo: 'L-036-EVOLVED',
      evolvedDescription: 'Reveal all enemy intents. Apply Vulnerable 4 to all. Vulnerable does not decay this combat.',
    },
  },
  {
    id: 'L-037',
    name: 'Sun\'s Blessing',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Max Lumens per Channel card increased by 3 (cap 8).',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 5,
      conditionText: 'Survived 5 combats',
      evolvesTo: 'L-037-EVOLVED',
      evolvedDescription: 'Max Lumens per Channel card increased by 5 (cap 10). Cards gain 1 Lumen when they retain.',
    },
  },
  {
    id: 'L-038',
    name: 'Divine Intervention',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'When you would die this combat, survive at 1 HP and gain 5 Lumens distributed. Exhaust.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 1,
      conditionText: 'Triggered once',
      evolvesTo: 'L-038-EVOLVED',
      evolvedDescription: 'When you would die this combat, survive at 10 HP and gain 5 Lumens distributed.',
    },
  },
  {
    id: 'L-039',
    name: 'Godlight',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Channel. Deal 15 damage. Release: +8 damage per Lumen. Heal for half damage dealt.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'release_with_condition',
      threshold: 5,
      conditionText: 'Released at 5 Lumens',
      evolvesTo: 'L-039-EVOLVED',
      evolvedDescription: 'Channel. Deal 15 damage. Release: +8 damage per Lumen. Heal for full damage dealt.',
    },
  },
  {
    id: 'L-040',
    name: 'Apex',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Trigger Release on every Channel card in hand simultaneously. They are not discarded.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    evolutionRule: {
      triggerType: 'trigger_with_condition',
      threshold: 5,
      conditionText: 'Triggered with 5+ Channel cards',
      evolvesTo: 'L-040-EVOLVED',
      evolvedDescription: 'Trigger Release on every Channel card in hand twice. They are not discarded.',
    },
  },
];

export const LUMINAR_EVOLVED_CARDS: Card[] = [
  {
    id: 'L-001-EVOLVED',
    name: 'Starlance',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 9 damage.',
    archetype: 'Basic',
    factionId: 'Luminar',
    basedOn: 'L-001',
  },
  {
    id: 'L-002-EVOLVED',
    name: 'Dawn Ward',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 7 Block. Gain 1 Lumen on a Channel card in hand.',
    archetype: 'Basic',
    factionId: 'Luminar',
    basedOn: 'L-002',
  },
  {
    id: 'L-003-EVOLVED',
    name: 'Deep Focus',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Draw 2 cards. Gain 2 Lumens on each Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-003',
  },
  {
    id: 'L-004-EVOLVED',
    name: 'Prism Lance',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Channel. Deal 8 damage. Release: +3 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-004',
  },
  {
    id: 'L-005-EVOLVED',
    name: 'Effulgence',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 2 Lumens on every Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-005',
  },
  {
    id: 'L-006-EVOLVED',
    name: 'Celestial Ward',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Channel. Gain 8 Block. Release: +3 Block per Lumen.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-006',
  },
  {
    id: 'L-007-EVOLVED',
    name: 'Broadbeam',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 5 damage to all enemies.',
    archetype: 'Support',
    factionId: 'Luminar',
    basedOn: 'L-007',
  },
  {
    id: 'L-008-EVOLVED',
    name: 'Incantation',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'The next Channel card you play this turn is treated as having +3 Lumens.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    basedOn: 'L-008',
  },
  {
    id: 'L-009-EVOLVED',
    name: 'First Light',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 2 Lumens on a Channel card in hand. Draw 1 card.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-009',
  },
  {
    id: 'L-010-EVOLVED',
    name: 'Aria',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Heal 5 HP. Gain 1 Lumen on every Channel card in hand.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-010',
  },
  {
    id: 'L-011-EVOLVED',
    name: 'Glare',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Channel. Deal 10 damage. Release: +5 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-011',
  },
  {
    id: 'L-012-EVOLVED',
    name: 'Constant Flame',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Channel. Gain 5 Block. Retain. Gain 1 Lumen when retained.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-012',
  },
  {
    id: 'L-013-EVOLVED',
    name: 'Resonance',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Transfer Lumens freely between Channel cards. Each transfer adds +1 Lumen.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    basedOn: 'L-013',
  },
  {
    id: 'L-014-EVOLVED',
    name: 'Severing Ray',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 14 damage. +3 damage for each Channel card in hand.',
    archetype: 'Support',
    factionId: 'Luminar',
    basedOn: 'L-014',
  },
  {
    id: 'L-015-EVOLVED',
    name: 'Dawnbreak',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 10 Block. Draw 1 card if at full HP.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-015',
  },
  {
    id: 'L-016-EVOLVED',
    name: 'Tranquility',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'End turn. Draw 3 cards next turn. Gain 2 Lumens on every Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-016',
  },
  {
    id: 'L-017-EVOLVED',
    name: 'Sunflare',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Channel. Deal 12 damage. Release: +4 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-017',
  },
  {
    id: 'L-018-EVOLVED',
    name: 'Corona',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Channel. Apply Vulnerable 2 and Weak 1 to all. Release: +1 each per Lumen.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    basedOn: 'L-018',
  },
  {
    id: 'L-019-EVOLVED',
    name: 'Sacred Mantra',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 1,
    description: 'The first card you play each turn gains Channel and 2 Lumens.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-019',
  },
  {
    id: 'L-020-EVOLVED',
    name: 'Convergence',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Gain 5 Lumens distributed freely across Channel cards in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-020',
  },
  {
    id: 'L-021-EVOLVED',
    name: 'Thunderbolt',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 18 damage. Exhaust.',
    archetype: 'Support',
    factionId: 'Luminar',
    basedOn: 'L-021',
  },
  {
    id: 'L-022-EVOLVED',
    name: 'Sunring',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'At end of turn, gain double Block from total Lumens in hand.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-022',
  },
  {
    id: 'L-023-EVOLVED',
    name: 'Supernova Flash',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Apply Weak 3 and Vulnerable 3 to all enemies. No Lumen cost.',
    archetype: 'Support',
    factionId: 'Luminar',
    basedOn: 'L-023',
  },
  {
    id: 'L-024-EVOLVED',
    name: 'Mandala',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'The next Release effect this turn triggers three times.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    basedOn: 'L-024',
  },
  {
    id: 'L-025-EVOLVED',
    name: 'Starpath',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 0,
    description: 'Discard your hand, draw 4 cards. Drawn Channel cards gain 2 Lumens.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-025',
  },
  {
    id: 'L-026-EVOLVED',
    name: 'Meteor Shower',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Channel. Deal 6 damage 3 times. Release: +3 damage per hit per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-026',
  },
  {
    id: 'L-027-EVOLVED',
    name: 'Everlight (power)',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Channel cards automatically Retain. +1 Lumen each time they retain.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-027',
  },
  {
    id: 'L-028-EVOLVED',
    name: 'Laser Focus',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Channel. Deal 25 damage. Release: Apply Weak 1 per Lumen.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    basedOn: 'L-028',
  },
  {
    id: 'L-029-EVOLVED',
    name: 'Moonlit Aegis',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Gain 20 Block. Gain 2 Lumens on every Channel card in hand.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-029',
  },
  {
    id: 'L-030-EVOLVED',
    name: 'Clarity',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Draw cards equal to total Lumens + 1 on Channel cards in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-030',
  },
  {
    id: 'L-031-EVOLVED',
    name: 'Galactic Collapse',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Channel. Deal 25 damage to all enemies. Release: +12 damage per Lumen.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-031',
  },
  {
    id: 'L-032-EVOLVED',
    name: 'Eternal Dawn',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At turn start, gain 2 Lumens on every Channel card in hand.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-032',
  },
  {
    id: 'L-033-EVOLVED',
    name: 'Ascension',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'Choose 2 Channel cards in your draw pile. Play them immediately, ignoring cost.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    basedOn: 'L-033',
  },
  {
    id: 'L-034-EVOLVED',
    name: 'Event Horizon',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'All Release effects are tripled.',
    archetype: 'Lightweave',
    factionId: 'Luminar',
    basedOn: 'L-034',
  },
  {
    id: 'L-035-EVOLVED',
    name: 'Celestial Form',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'The first attack that would damage you each turn is reduced to 0. Gain 2 Lumens when this triggers.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-035',
  },
  {
    id: 'L-036-EVOLVED',
    name: 'Omniscience',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'Reveal all enemy intents. Apply Vulnerable 4 to all. Vulnerable does not decay this combat.',
    archetype: 'Support',
    factionId: 'Luminar',
    basedOn: 'L-036',
  },
  {
    id: 'L-037-EVOLVED',
    name: 'Solar Blessing',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Max Lumens per Channel card increased by 5 (cap 10). Cards gain 1 Lumen when they retain.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-037',
  },
  {
    id: 'L-038-EVOLVED',
    name: 'Providence',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'When you would die this combat, survive at 10 HP and gain 5 Lumens distributed.',
    archetype: 'Radiant Shield',
    factionId: 'Luminar',
    basedOn: 'L-038',
  },
  {
    id: 'L-039-EVOLVED',
    name: 'Divine Light',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Channel. Deal 15 damage. Release: +8 damage per Lumen. Heal for full damage dealt.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-039',
  },
  {
    id: 'L-040-EVOLVED',
    name: 'Zenith',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Trigger Release on every Channel card in hand twice. They are not discarded.',
    archetype: 'Channel Storm',
    factionId: 'Luminar',
    basedOn: 'L-040',
  },
];

export const LUMINAR_CARDS: Card[] = [
  ...LUMINAR_BASE_CARDS,
  ...LUMINAR_EVOLVED_CARDS,
];
