// Auto-generated from docs/roguelite/factions/pyroclast-cards.xlsx.
// Do not hand-edit — re-run the generator (docs/roguelite/01-card-content-notes.md).

import type { Card } from '../types';

export const PYROCLAST_BASE_CARDS: Card[] = [
  {
    id: 'P-001',
    name: 'Cinder Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 6 damage.',
    archetype: 'Basic',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'P-001-EVOLVED',
      evolvedDescription: 'Deal 9 damage.',
    },
  },
  {
    id: 'P-002',
    name: 'Scale Guard',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 5 Block.',
    archetype: 'Basic',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'P-002-EVOLVED',
      evolvedDescription: 'Gain 7 Block and 1 Heat.',
    },
  },
  {
    id: 'P-003',
    name: 'Kindle',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Gain 3 Heat.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-003-EVOLVED',
      evolvedDescription: 'Gain 4 Heat. Next attack this turn deals +2 damage.',
    },
  },
  {
    id: 'P-004',
    name: 'Flame Lash',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 8 damage. If Heat >= 3, apply Ignite 2.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 6,
      conditionText: 'Played 6 times at Heat >= 5',
      evolvesTo: 'P-004-EVOLVED',
      evolvedDescription: 'Deal 10 damage. Apply Ignite 3.',
    },
  },
  {
    id: 'P-005',
    name: 'Ember Volley',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 3 damage 3 times.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'P-005-EVOLVED',
      evolvedDescription: 'Deal 4 damage 3 times.',
    },
  },
  {
    id: 'P-006',
    name: 'Ash Cloud',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Apply 2 Weak to all enemies.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'hold_then_play',
      threshold: 3,
      conditionText: 'Held 3 turns then played',
      evolvesTo: 'P-006-EVOLVED',
      evolvedDescription: 'Apply 2 Weak to all enemies. Gain 5 Block.',
    },
  },
  {
    id: 'P-007',
    name: 'Oil Flask',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Your next Attack applies Ignite 2.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'P-007-EVOLVED',
      evolvedDescription: 'Your next 2 Attacks apply Ignite 2.',
    },
  },
  {
    id: 'P-008',
    name: 'Magma Fist',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 13 damage.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'P-008-EVOLVED',
      evolvedDescription: 'Deal 16 damage. Apply Ignite 2.',
    },
  },
  {
    id: 'P-009',
    name: 'Heat Shimmer',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 4 Block and 1 Heat.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'P-009-EVOLVED',
      evolvedDescription: 'Gain 6 Block and 2 Heat.',
    },
  },
  {
    id: 'P-010',
    name: 'Blazing Charge',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 4 damage + 4 per Heat spent (up to 5 Heat).',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 5,
      conditionText: 'Played 5 times spending Heat',
      evolvesTo: 'P-010-EVOLVED',
      evolvedDescription: 'Deal 4 damage + 6 per Heat spent (up to 5 Heat).',
    },
  },
  {
    id: 'P-011',
    name: 'Cauterize',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Heal 4 HP. Take 2 damage.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'P-011-EVOLVED',
      evolvedDescription: 'Heal 6 HP. Take 1 damage.',
    },
  },
  {
    id: 'P-012',
    name: 'Spark',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Gain 1 Heat. Draw 1 card.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 6,
      conditionText: 'Played 6 times at Heat >= 4',
      evolvesTo: 'P-012-EVOLVED',
      evolvedDescription: 'Gain 2 Heat. Draw 1 card.',
    },
  },
  {
    id: 'P-013',
    name: 'Hot Wind',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Deal 2 damage to all enemies. Gain 1 Heat.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'P-013-EVOLVED',
      evolvedDescription: 'Deal 3 damage to all enemies. Gain 2 Heat.',
    },
  },
  {
    id: 'P-014',
    name: 'Pyre Lance',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 14 damage. Consume all Heat.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-014-EVOLVED',
      evolvedDescription: 'Deal 14 damage + damage equal to Heat consumed.',
    },
  },
  {
    id: 'P-015',
    name: 'Rekindle',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Return a Pyroclast card from your discard pile to your hand.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-015-EVOLVED',
      evolvedDescription: 'Return any card from your discard pile to your hand.',
    },
  },
  {
    id: 'P-016',
    name: 'Glowing Resolve',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 3 Block per Heat (up to 4 Heat counted).',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'P-016-EVOLVED',
      evolvedDescription: 'Gain 4 Block per Heat (up to 4 Heat counted).',
    },
  },
  {
    id: 'P-017',
    name: 'Dragonbreath',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 7 damage to all enemies.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'P-017-EVOLVED',
      evolvedDescription: 'Deal 9 damage to all enemies. Apply Ignite 1 to all.',
    },
  },
  {
    id: 'P-018',
    name: 'Forge Heart',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Whenever you gain Heat, gain 1 Block.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 20,
      conditionText: 'Triggered 20 times',
      evolvesTo: 'P-018-EVOLVED',
      evolvedDescription: 'Whenever you gain Heat, gain 1 Block. Gain 1 Strength at Heat 10+.',
    },
  },
  {
    id: 'P-019',
    name: 'Molten Skin',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 1,
    description: 'At end of turn, if you have Block, gain 2 Heat.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 15,
      conditionText: 'Triggered 15 times',
      evolvesTo: 'P-019-EVOLVED',
      evolvedDescription: 'At end of turn, if you have Block, gain 2 Heat. Keep 5 Block next turn.',
    },
  },
  {
    id: 'P-020',
    name: 'Overclock',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Draw 2 cards. Apply Ignite 2 to yourself.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-020-EVOLVED',
      evolvedDescription: 'Draw 3 cards. Apply Ignite 2 to yourself.',
    },
  },
  {
    id: 'P-021',
    name: 'Pyroclasm',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 9 damage to all enemies. Spend 5 Heat for +6 damage to each.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 4,
      conditionText: 'Played 4 times spending Heat',
      evolvesTo: 'P-021-EVOLVED',
      evolvedDescription: 'Deal 11 damage to all enemies. Spend 5 Heat for +8 damage to each.',
    },
  },
  {
    id: 'P-022',
    name: 'Soot Burst',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 0,
    description: 'Apply Vulnerable 1 to all enemies.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'P-022-EVOLVED',
      evolvedDescription: 'Apply Vulnerable 2 to all enemies.',
    },
  },
  {
    id: 'P-023',
    name: 'Meltdown',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 3,
    description: 'Deal damage equal to your current Heat x 3.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 3,
      conditionText: 'Played 3 times at Heat >= 8',
      evolvesTo: 'P-023-EVOLVED',
      evolvedDescription: 'Deal damage equal to your current Heat x 4.',
    },
  },
  {
    id: 'P-024',
    name: 'Glass Cannon',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Your next Attack deals +12 damage. Lose 5 HP.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-024-EVOLVED',
      evolvedDescription: 'Your next Attack deals +15 damage. Lose 3 HP.',
    },
  },
  {
    id: 'P-025',
    name: 'Combustion',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 10 damage. If target has Ignite, trigger it immediately.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 5,
      conditionText: 'Played 5 times triggering Ignite',
      evolvesTo: 'P-025-EVOLVED',
      evolvedDescription: 'Deal 10 damage. If target has Ignite, trigger it and spread remaining to all enemies.',
    },
  },
  {
    id: 'P-026',
    name: 'Ash Dancer',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 7 damage. If this kills the target, draw 2 cards.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'kill_count',
      threshold: 3,
      conditionText: 'Killed 3 targets with this',
      evolvesTo: 'P-026-EVOLVED',
      evolvedDescription: 'Deal 9 damage. If this kills the target, draw 2 cards.',
    },
  },
  {
    id: 'P-027',
    name: 'Fuel the Flames',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Exhaust a card from hand. Gain 3 Heat per its cost.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-027-EVOLVED',
      evolvedDescription: 'Exhaust a card from hand. Gain 4 Heat per its cost.',
    },
  },
  {
    id: 'P-028',
    name: 'Searing Resolve',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Gain 8 Block. If at full HP, gain 3 Heat.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 5,
      conditionText: 'Played 5 times at full HP',
      evolvesTo: 'P-028-EVOLVED',
      evolvedDescription: 'Gain 10 Block and 3 Heat.',
    },
  },
  {
    id: 'P-029',
    name: 'Incinerator',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 9 damage. Exhaust. If this kills, add a copy to hand.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 3,
      conditionText: 'Triggered kill effect 3 times',
      evolvesTo: 'P-029-EVOLVED',
      evolvedDescription: 'Deal 9 damage. Exhaust. If this kills, add 2 copies to hand.',
    },
  },
  {
    id: 'P-030',
    name: 'Spirit of Fire',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'At turn start, gain 2 Heat.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 5,
      conditionText: 'Survived 5 combats with this',
      evolvesTo: 'P-030-EVOLVED',
      evolvedDescription: 'At turn start, gain 3 Heat. Once per combat, survive lethal at 10 HP.',
    },
  },
  {
    id: 'P-031',
    name: 'Sunfire Blade',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal 18 damage and apply Ignite 4.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_in_boss',
      threshold: 3,
      conditionText: 'Played in 3 boss fights',
      evolvesTo: 'P-031-EVOLVED',
      evolvedDescription: 'Deal 22 damage and apply Ignite 5.',
    },
  },
  {
    id: 'P-032',
    name: 'Volcano',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'At start of each turn, deal 4 damage to all enemies.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'P-032-EVOLVED',
      evolvedDescription: 'At start of each turn, deal 6 damage to all enemies.',
    },
  },
  {
    id: 'P-033',
    name: 'Immolate',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal 22 damage. Shuffle 2 Burn cards into your discard pile.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'P-033-EVOLVED',
      evolvedDescription: 'Deal 28 damage. Shuffle 2 Burn cards (dealing half damage) into discard.',
    },
  },
  {
    id: 'P-034',
    name: 'Phoenix Form',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Once per combat, when reduced to 0 HP, restore 15 HP and gain 3 Heat.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'revived',
      threshold: 1,
      conditionText: 'Revived at least once',
      evolvesTo: 'P-034-EVOLVED',
      evolvedDescription: 'Once per combat, when reduced to 0 HP, restore 25 HP and gain 5 Heat.',
    },
  },
  {
    id: 'P-035',
    name: 'Ring of Fire',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'Whenever attacked, deal 2 damage back. Deal 4 if Heat >= 5.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 20,
      conditionText: 'Triggered 20 times',
      evolvesTo: 'P-035-EVOLVED',
      evolvedDescription: 'Whenever attacked, deal 4 damage back. Deal 6 if Heat >= 5.',
    },
  },
  {
    id: 'P-036',
    name: 'Sun\'s Fury',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 28 damage. If Heat >= 8, deal 14 more damage.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 3,
      conditionText: 'Played 3 times with Heat >= 8',
      evolvesTo: 'P-036-EVOLVED',
      evolvedDescription: 'Deal 32 damage. If Heat >= 6, deal 14 more damage.',
    },
  },
  {
    id: 'P-037',
    name: 'Forge Master',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'Every 3 Heat spent this combat, draw 1 card.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'draw_via_this',
      threshold: 10,
      conditionText: 'Drew 10 cards via this effect',
      evolvesTo: 'P-037-EVOLVED',
      evolvedDescription: 'Every 2 Heat spent this combat, draw 1 card.',
    },
  },
  {
    id: 'P-038',
    name: 'Everburn',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'Combat starts with 5 Heat. Gain 1 Heat at turn start.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 5,
      conditionText: 'Survived 5 combats with this',
      evolvesTo: 'P-038-EVOLVED',
      evolvedDescription: 'Combat starts with 8 Heat. Gain 2 Heat at turn start.',
    },
  },
  {
    id: 'P-039',
    name: 'Magma Tide',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal damage equal to Heat to 3 random enemies.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-039-EVOLVED',
      evolvedDescription: 'Deal damage equal to Heat to 4 chosen enemies.',
    },
  },
  {
    id: 'P-040',
    name: 'Dragon\'s Roar',
    rarity: 'Rare',
    type: 'Attack',
    cost: 1,
    description: 'Apply Vulnerable 3 to all enemies. Gain 4 Heat.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'P-040-EVOLVED',
      evolvedDescription: 'Apply Vulnerable 4 and Weak 2 to all enemies. Gain 5 Heat.',
    },
  },
];

export const PYROCLAST_EVOLVED_CARDS: Card[] = [
  {
    id: 'P-001-EVOLVED',
    name: 'Blazing Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 9 damage.',
    archetype: 'Basic',
    factionId: 'Pyroclast',
    basedOn: 'P-001',
  },
  {
    id: 'P-002-EVOLVED',
    name: 'Ember Ward',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 7 Block and 1 Heat.',
    archetype: 'Basic',
    factionId: 'Pyroclast',
    basedOn: 'P-002',
  },
  {
    id: 'P-003-EVOLVED',
    name: 'Stoke',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Gain 4 Heat. Next attack this turn deals +2 damage.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-003',
  },
  {
    id: 'P-004-EVOLVED',
    name: 'Scorching Lash',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 10 damage. Apply Ignite 3.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    basedOn: 'P-004',
  },
  {
    id: 'P-005-EVOLVED',
    name: 'Firestorm Volley',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 4 damage 3 times.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    basedOn: 'P-005',
  },
  {
    id: 'P-006-EVOLVED',
    name: 'Smokescreen',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Apply 2 Weak to all enemies. Gain 5 Block.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    basedOn: 'P-006',
  },
  {
    id: 'P-007-EVOLVED',
    name: 'Naphtha Flask',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Your next 2 Attacks apply Ignite 2.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    basedOn: 'P-007',
  },
  {
    id: 'P-008-EVOLVED',
    name: 'Volcanic Fist',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 16 damage. Apply Ignite 2.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-008',
  },
  {
    id: 'P-009-EVOLVED',
    name: 'Mirage',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 6 Block and 2 Heat.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-009',
  },
  {
    id: 'P-010-EVOLVED',
    name: 'Inferno Charge',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 4 damage + 6 per Heat spent (up to 5 Heat).',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-010',
  },
  {
    id: 'P-011-EVOLVED',
    name: 'Sear Shut',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Heal 6 HP. Take 1 damage.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    basedOn: 'P-011',
  },
  {
    id: 'P-012-EVOLVED',
    name: 'Flare',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Gain 2 Heat. Draw 1 card.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-012',
  },
  {
    id: 'P-013-EVOLVED',
    name: 'Scirocco',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Deal 3 damage to all enemies. Gain 2 Heat.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    basedOn: 'P-013',
  },
  {
    id: 'P-014-EVOLVED',
    name: 'Sunspear',
    rarity: 'Common',
    type: 'Attack',
    cost: 2,
    description: 'Deal 14 damage + damage equal to Heat consumed.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-014',
  },
  {
    id: 'P-015-EVOLVED',
    name: 'Eternal Flame',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Return any card from your discard pile to your hand.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    basedOn: 'P-015',
  },
  {
    id: 'P-016-EVOLVED',
    name: 'Armored Core',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 4 Block per Heat (up to 4 Heat counted).',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-016',
  },
  {
    id: 'P-017-EVOLVED',
    name: 'Wyrmbreath',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 9 damage to all enemies. Apply Ignite 1 to all.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    basedOn: 'P-017',
  },
  {
    id: 'P-018-EVOLVED',
    name: 'Forge Soul',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Whenever you gain Heat, gain 1 Block. Gain 1 Strength at Heat 10+.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    basedOn: 'P-018',
  },
  {
    id: 'P-019-EVOLVED',
    name: 'Obsidian Skin',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 1,
    description: 'At end of turn, if you have Block, gain 2 Heat. Keep 5 Block next turn.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    basedOn: 'P-019',
  },
  {
    id: 'P-020-EVOLVED',
    name: 'Burnout Drive',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Draw 3 cards. Apply Ignite 2 to yourself.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    basedOn: 'P-020',
  },
  {
    id: 'P-021-EVOLVED',
    name: 'Cataclysm',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 11 damage to all enemies. Spend 5 Heat for +8 damage to each.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-021',
  },
  {
    id: 'P-022-EVOLVED',
    name: 'Ashstorm',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 0,
    description: 'Apply Vulnerable 2 to all enemies.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    basedOn: 'P-022',
  },
  {
    id: 'P-023-EVOLVED',
    name: 'Reactor Breach',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 3,
    description: 'Deal damage equal to your current Heat x 4.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-023',
  },
  {
    id: 'P-024-EVOLVED',
    name: 'Flame Cannon',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Your next Attack deals +15 damage. Lose 3 HP.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    basedOn: 'P-024',
  },
  {
    id: 'P-025-EVOLVED',
    name: 'Chain Combustion',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 10 damage. If target has Ignite, trigger it and spread remaining to all enemies.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    basedOn: 'P-025',
  },
  {
    id: 'P-026-EVOLVED',
    name: 'Ember Dancer',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 9 damage. If this kills the target, draw 2 cards.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    basedOn: 'P-026',
  },
  {
    id: 'P-027-EVOLVED',
    name: 'Pyre Tribute',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Exhaust a card from hand. Gain 4 Heat per its cost.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-027',
  },
  {
    id: 'P-028-EVOLVED',
    name: 'Unbreaking',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Gain 10 Block and 3 Heat.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    basedOn: 'P-028',
  },
  {
    id: 'P-029-EVOLVED',
    name: 'Propagator',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 9 damage. Exhaust. If this kills, add 2 copies to hand.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    basedOn: 'P-029',
  },
  {
    id: 'P-030-EVOLVED',
    name: 'Phoenix Spirit',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'At turn start, gain 3 Heat. Once per combat, survive lethal at 10 HP.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-030',
  },
  {
    id: 'P-031-EVOLVED',
    name: 'Solar Edge',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal 22 damage and apply Ignite 5.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    basedOn: 'P-031',
  },
  {
    id: 'P-032-EVOLVED',
    name: 'Caldera',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'At start of each turn, deal 6 damage to all enemies.',
    archetype: 'Ignite Stack',
    factionId: 'Pyroclast',
    basedOn: 'P-032',
  },
  {
    id: 'P-033-EVOLVED',
    name: 'Self-Immolate',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal 28 damage. Shuffle 2 Burn cards (dealing half damage) into discard.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    basedOn: 'P-033',
  },
  {
    id: 'P-034-EVOLVED',
    name: 'Eternal Phoenix',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Once per combat, when reduced to 0 HP, restore 25 HP and gain 5 Heat.',
    archetype: 'Self-Burn',
    factionId: 'Pyroclast',
    basedOn: 'P-034',
  },
  {
    id: 'P-035-EVOLVED',
    name: 'Ring of Ashes',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'Whenever attacked, deal 4 damage back. Deal 6 if Heat >= 5.',
    archetype: 'Overheat Tank',
    factionId: 'Pyroclast',
    basedOn: 'P-035',
  },
  {
    id: 'P-036-EVOLVED',
    name: 'Solar Flare',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 32 damage. If Heat >= 6, deal 14 more damage.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-036',
  },
  {
    id: 'P-037-EVOLVED',
    name: 'Grand Forgemaster',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'Every 2 Heat spent this combat, draw 1 card.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-037',
  },
  {
    id: 'P-038-EVOLVED',
    name: 'Wildfire',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'Combat starts with 8 Heat. Gain 2 Heat at turn start.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-038',
  },
  {
    id: 'P-039-EVOLVED',
    name: 'Lava Tide',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal damage equal to Heat to 4 chosen enemies.',
    archetype: 'Heat Snowball',
    factionId: 'Pyroclast',
    basedOn: 'P-039',
  },
  {
    id: 'P-040-EVOLVED',
    name: 'Tyrant\'s Roar',
    rarity: 'Rare',
    type: 'Attack',
    cost: 1,
    description: 'Apply Vulnerable 4 and Weak 2 to all enemies. Gain 5 Heat.',
    archetype: 'Support',
    factionId: 'Pyroclast',
    basedOn: 'P-040',
  },
];

export const PYROCLAST_CARDS: Card[] = [
  ...PYROCLAST_BASE_CARDS,
  ...PYROCLAST_EVOLVED_CARDS,
];
