// Auto-generated from docs/roguelite/factions/warp-riders-cards.xlsx.
// Do not hand-edit — re-run the generator (docs/roguelite/01-card-content-notes.md).

import type { Card } from '../types';

export const WARPRIDERS_BASE_CARDS: Card[] = [
  {
    id: 'W-001',
    name: 'Glitch Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Flux. A: Deal 4 damage. B: Deal 8 damage. C: Deal 6 damage and draw 1 card.',
    archetype: 'Basic',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Deal 4 damage.',
      B: 'Deal 8 damage.',
      C: 'Deal 6 damage and draw 1 card.',
    },
    evolutionRule: {
      triggerType: 'play_all_flux_states',
      threshold: 1,
      conditionText: 'Played in all 3 states',
      evolvesTo: 'W-001-EVOLVED',
      evolvedDescription: 'Flux. A: Deal 5. B: Deal 10. C: Deal 7 and draw 1.',
    },
  },
  {
    id: 'W-002',
    name: 'Warp Step',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Flux. A: Gain 5 Block. B: Gain 3 Block and 1 Energy next turn. C: Gain 7 Block.',
    archetype: 'Basic',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Gain 5 Block.',
      B: 'Gain 3 Block and 1 Energy next turn.',
      C: 'Gain 7 Block.',
    },
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 8,
      conditionText: 'Played 8 times',
      evolvesTo: 'W-002-EVOLVED',
      evolvedDescription: 'Flux. A: Gain 7 Block. B: Gain 5 Block and 1 Energy next turn. C: Gain 9 Block.',
    },
  },
  {
    id: 'W-003',
    name: 'Twist',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Reroll the state of all Flux cards in your hand.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-003-EVOLVED',
      evolvedDescription: 'Reroll all Flux cards in hand. The next Flux card you play this turn locks to a state of your choice.',
    },
  },
  {
    id: 'W-004',
    name: 'Unstable Bolt',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 3 to 10 damage (random).',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'W-004-EVOLVED',
      evolvedDescription: 'Deal 5 to 12 damage (random).',
    },
  },
  {
    id: 'W-005',
    name: 'Pocket Dim',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Remove a card from combat. It returns to your hand at the start of next turn.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-005-EVOLVED',
      evolvedDescription: 'Remove 2 cards from combat. They return to hand next turn.',
    },
  },
  {
    id: 'W-006',
    name: 'Phase Slash',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 6 damage. Shuffle this card into your draw pile.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'W-006-EVOLVED',
      evolvedDescription: 'Deal 8 damage. Shuffle this card into your draw pile.',
    },
  },
  {
    id: 'W-007',
    name: 'Echo',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Add a copy of the last card played this combat to your hand.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'W-007-EVOLVED',
      evolvedDescription: 'Add a copy of each of the last 2 cards played this combat to your hand.',
    },
  },
  {
    id: 'W-008',
    name: 'Spatial Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Flux. A: Deal 8 damage. B: Deal 3 damage twice. C: Deal 5 damage and draw 1 card.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Deal 8 damage.',
      B: 'Deal 3 damage twice.',
      C: 'Deal 5 damage and draw 1 card.',
    },
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-008-EVOLVED',
      evolvedDescription: 'Flux. A: Deal 10. B: Deal 4 twice. C: Deal 6 and draw 1.',
    },
  },
  {
    id: 'W-009',
    name: 'Reality Crack',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Deal 4 damage to all enemies. Open a random Rift for 2 turns.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'W-009-EVOLVED',
      evolvedDescription: 'Deal 5 damage to all enemies. Open 2 random Rifts for 2 turns.',
    },
  },
  {
    id: 'W-010',
    name: 'Void Whisper',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Choose one: gain 1 Energy OR draw 2 cards.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-010-EVOLVED',
      evolvedDescription: 'Gain 1 Energy and draw 1 card.',
    },
  },
  {
    id: 'W-011',
    name: 'Anomaly',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 4 to 12 damage (random).',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 10,
      conditionText: 'Played 10 times',
      evolvesTo: 'W-011-EVOLVED',
      evolvedDescription: 'Deal 6 to 14 damage (random).',
    },
  },
  {
    id: 'W-012',
    name: 'Stutter Step',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 6 Block. Reroll all Flux cards in hand.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-012-EVOLVED',
      evolvedDescription: 'Gain 8 Block. Reroll all Flux cards in hand.',
    },
  },
  {
    id: 'W-013',
    name: 'Warped Blade',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Flux. A: Deal 5 damage. B: Deal 7 damage. C: Deal 6 damage and apply Weak 1.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Deal 5 damage.',
      B: 'Deal 7 damage.',
      C: 'Deal 6 damage and apply Weak 1.',
    },
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'W-013-EVOLVED',
      evolvedDescription: 'Flux. A: Deal 7. B: Deal 9. C: Deal 8 and apply Weak 1.',
    },
  },
  {
    id: 'W-014',
    name: 'Fold Space',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Return a random card from your discard pile to your hand.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-014-EVOLVED',
      evolvedDescription: 'Return 2 random cards from your discard pile to your hand.',
    },
  },
  {
    id: 'W-015',
    name: 'Quantum Guard',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Flux. A: Gain 5 Block. B: Gain 8 Block. C: Gain 3 Block and 3 Block next turn.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Gain 5 Block.',
      B: 'Gain 8 Block.',
      C: 'Gain 3 Block and 3 Block next turn.',
    },
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'W-015-EVOLVED',
      evolvedDescription: 'Flux. A: Gain 7. B: Gain 10. C: Gain 4 and 4 next turn.',
    },
  },
  {
    id: 'W-016',
    name: 'Dimensional Rift',
    rarity: 'Common',
    type: 'Skill',
    cost: 2,
    description: 'Open a Cost Rift for 2 turns: 1 random card in your hand costs 0 each turn.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-016-EVOLVED',
      evolvedDescription: 'Open a Cost Rift for 3 turns: 2 random cards in your hand cost 0 each turn.',
    },
  },
  {
    id: 'W-017',
    name: 'Probability Wave',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'All Flux cards in your hand display their highest-value state this turn.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'W-017-EVOLVED',
      evolvedDescription: 'All Flux cards in your hand lock to their highest-value state for this turn.',
    },
  },
  {
    id: 'W-018',
    name: 'Event Horizon',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Flux cards in your hand no longer shift at turn start.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 3,
      conditionText: 'Survived 3 combats',
      evolvesTo: 'W-018-EVOLVED',
      evolvedDescription: 'Flux cards in your hand no longer shift. Gain 2 Block at turn start.',
    },
  },
  {
    id: 'W-019',
    name: 'Chaos Bolt',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 6 to 20 damage (random).',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 6,
      conditionText: 'Played 6 times',
      evolvesTo: 'W-019-EVOLVED',
      evolvedDescription: 'Deal 8 to 24 damage (random).',
    },
  },
  {
    id: 'W-020',
    name: 'Rift Walker',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Open 3 random Rifts for 2 turns each.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'W-020-EVOLVED',
      evolvedDescription: 'Open 3 random Rifts for 3 turns each.',
    },
  },
  {
    id: 'W-021',
    name: 'Paradox Strike',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 14 damage. 50% chance to take 6 self damage.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_with_condition',
      threshold: 5,
      conditionText: 'Played 5 times with no self-damage',
      evolvesTo: 'W-021-EVOLVED',
      evolvedDescription: 'Deal 18 damage. 50% chance to take 4 self damage.',
    },
  },
  {
    id: 'W-022',
    name: 'Time Skip',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Skip the next turn of one enemy. Exhaust.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 3,
      conditionText: 'Played 3 times',
      evolvesTo: 'W-022-EVOLVED',
      evolvedDescription: 'Skip the next turn of up to 2 enemies. Exhaust.',
    },
  },
  {
    id: 'W-023',
    name: 'Tesseract',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Choose a Flux card in your hand. Lock it to the state of your choice for the rest of combat.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'W-023-EVOLVED',
      evolvedDescription: 'Choose 2 Flux cards in your hand. Lock each to a state of your choice for the rest of combat.',
    },
  },
  {
    id: 'W-024',
    name: 'Dimensional Shield',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Flux. A: Gain 20 Block. B: Gain 10 Block and Retain. C: Gain 15 Block and 1 Energy next turn.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Gain 20 Block.',
      B: 'Gain 10 Block and Retain.',
      C: 'Gain 15 Block and 1 Energy next turn.',
    },
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-024-EVOLVED',
      evolvedDescription: 'Flux. A: Gain 24. B: Gain 12 and Retain. C: Gain 18 and 1 Energy next turn.',
    },
  },
  {
    id: 'W-025',
    name: 'Warp Strike',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Flux. A: Deal 18 damage. B: Deal 10 damage and apply Vulnerable 2. C: Deal 12 damage twice.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Deal 18 damage.',
      B: 'Deal 10 damage and apply Vulnerable 2.',
      C: 'Deal 12 damage twice.',
    },
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 5,
      conditionText: 'Played 5 times',
      evolvesTo: 'W-025-EVOLVED',
      evolvedDescription: 'Flux. A: Deal 22. B: Deal 12 and Vulnerable 3. C: Deal 14 twice.',
    },
  },
  {
    id: 'W-026',
    name: 'Probability Reset',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Reroll all Flux cards in your hand and draw pile. Draw 2 cards.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'W-026-EVOLVED',
      evolvedDescription: 'Reroll all Flux cards in hand, draw, and discard. Draw 2 cards.',
    },
  },
  {
    id: 'W-027',
    name: 'Entropy',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Enemies\' telegraphed damage values are randomized each turn within their range.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'survived_combats',
      threshold: 3,
      conditionText: 'Survived 3 combats',
      evolvesTo: 'W-027-EVOLVED',
      evolvedDescription: 'Enemies\' damage is randomized and reduced by 1 per hit.',
    },
  },
  {
    id: 'W-028',
    name: 'Collapsing Star',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 8 to 20 damage to all enemies (random). Take 3 self damage.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'W-028-EVOLVED',
      evolvedDescription: 'Deal 10 to 24 damage to all enemies. Take 3 self damage.',
    },
  },
  {
    id: 'W-029',
    name: 'Singularity',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Flux. A: Draw 1 extra card each turn. B: Gain 1 extra Energy each turn. C: Gain 4 Block each turn.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    fluxStates: {
      A: 'Draw 1 extra card each turn.',
      B: 'Gain 1 extra Energy each turn.',
      C: 'Gain 4 Block each turn.',
    },
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'W-029-EVOLVED',
      evolvedDescription: 'Flux. A: Draw 2 extra. B: Gain 2 Energy. C: Gain 6 Block each turn.',
    },
  },
  {
    id: 'W-030',
    name: 'Mirror Self',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Add a copy of 2 cards from your hand to your hand. They cost 0 this turn.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 4,
      conditionText: 'Played 4 times',
      evolvesTo: 'W-030-EVOLVED',
      evolvedDescription: 'Add a copy of 3 cards from your hand to your hand. They cost 0 this turn.',
    },
  },
  {
    id: 'W-031',
    name: 'The Archer',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal 20 damage to one target. Ignore all evasion and positional effects. Your next Flux card locks to its current state.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'kill_count',
      threshold: 3,
      conditionText: 'Killed 3 enemies with this',
      evolvesTo: 'W-031-EVOLVED',
      evolvedDescription: 'Deal 24 damage to one target. Ignore all evasion and positional effects. Your next 2 Flux cards lock to their current states.',
    },
  },
  {
    id: 'W-032',
    name: 'Cosmic Choir',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Whenever a Flux card in your hand shifts state, deal 3 damage to a random enemy and gain 1 Block.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 20,
      conditionText: 'Triggered 20 times',
      evolvesTo: 'W-032-EVOLVED',
      evolvedDescription: 'Whenever a Flux card in your hand shifts state, deal 5 damage to a random enemy and gain 2 Block.',
    },
  },
  {
    id: 'W-033',
    name: 'The Burning Face of the World',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 40 damage to all enemies. Apply Vulnerable 2 to all. Open 3 random Rifts for 2 turns. Exhaust.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 2,
      conditionText: 'Played 2 times',
      evolvesTo: 'W-033-EVOLVED',
      evolvedDescription: 'Deal 55 damage to all enemies. Apply Vulnerable 3 to all. Open 4 random Rifts for 2 turns. Exhaust.',
    },
  },
  {
    id: 'W-034',
    name: 'Mistress of the Mysteries',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At start of each turn, reveal the top card of your draw pile. Once per turn, you may play that card from the top of your draw pile for 1 less Energy (min 0).',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'ability_use_count',
      threshold: 8,
      conditionText: 'Used ability 8 times',
      evolvesTo: 'W-034-EVOLVED',
      evolvedDescription: 'At start of each turn, reveal the top 2 cards. Once per turn, play either for 1 less Energy (min 0).',
    },
  },
  {
    id: 'W-035',
    name: 'Omniverse Slash',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 8 damage to target 5 times. Each hit independently has a 50% chance to deal double damage.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 3,
      conditionText: 'Played with 3+ double hits triggered',
      evolvesTo: 'W-035-EVOLVED',
      evolvedDescription: 'Deal 10 damage to target 5 times. Each hit has a 50% chance to deal double damage.',
    },
  },
  {
    id: 'W-036',
    name: 'Rift Master',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'All Rifts you open last twice as long and their effects are doubled.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'rift_open_count',
      threshold: 10,
      conditionText: 'Opened 10 Rifts',
      evolvesTo: 'W-036-EVOLVED',
      evolvedDescription: 'All Rifts you open last three times as long and their effects are tripled.',
    },
  },
  {
    id: 'W-037',
    name: 'Schrödinger',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'This turn: all damage dealt and taken is multiplied by 0 or 2 (50/50 roll). Exhaust.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'trigger_with_condition',
      threshold: 2,
      conditionText: 'Triggered 2x outcome 3 times',
      evolvesTo: 'W-037-EVOLVED',
      evolvedDescription: 'This turn: all damage dealt and taken is multiplied by 0 or 2 (33/66 in your favor). Exhaust.',
    },
  },
  {
    id: 'W-038',
    name: 'Chrono Break',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Replay every card play from your previous turn in the same order. Exhaust.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 2,
      conditionText: 'Played 2 times',
      evolvesTo: 'W-038-EVOLVED',
      evolvedDescription: 'Replay every card play from your previous 2 turns in order. Exhaust.',
    },
  },
  {
    id: 'W-039',
    name: 'Reality Anchor',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At start of each turn, lock one Flux card in your hand to a state of your choice.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'trigger_count',
      threshold: 10,
      conditionText: 'Triggered 10 times',
      evolvesTo: 'W-039-EVOLVED',
      evolvedDescription: 'At start of each turn, lock 2 Flux cards in your hand to states of your choice.',
    },
  },
  {
    id: 'W-040',
    name: 'Genesis Bolt',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 25 damage to all enemies. Apply Weak 2, Vulnerable 2, and 4 Burn to all enemies. Open a Genesis Rift for 1 turn (all cards cost -1 Energy).',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    evolutionRule: {
      triggerType: 'play_count',
      threshold: 2,
      conditionText: 'Played 2 times',
      evolvesTo: 'W-040-EVOLVED',
      evolvedDescription: 'Deal 30 damage to all enemies. Apply Weak 3, Vulnerable 3, and 5 Burn. Open 2 Genesis Rifts.',
    },
  },
];

export const WARPRIDERS_EVOLVED_CARDS: Card[] = [
  {
    id: 'W-001-EVOLVED',
    name: 'Stutter Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Flux. A: Deal 5. B: Deal 10. C: Deal 7 and draw 1.',
    archetype: 'Basic',
    factionId: 'WarpRiders',
    basedOn: 'W-001',
    fluxStates: {
      A: 'Deal 5.',
      B: 'Deal 10.',
      C: 'Deal 7 and draw 1.',
    },
  },
  {
    id: 'W-002-EVOLVED',
    name: 'Phase Step',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Flux. A: Gain 7 Block. B: Gain 5 Block and 1 Energy next turn. C: Gain 9 Block.',
    archetype: 'Basic',
    factionId: 'WarpRiders',
    basedOn: 'W-002',
    fluxStates: {
      A: 'Gain 7 Block.',
      B: 'Gain 5 Block and 1 Energy next turn.',
      C: 'Gain 9 Block.',
    },
  },
  {
    id: 'W-003-EVOLVED',
    name: 'Warp Twist',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Reroll all Flux cards in hand. The next Flux card you play this turn locks to a state of your choice.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-003',
  },
  {
    id: 'W-004-EVOLVED',
    name: 'Chaos Bolt',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 5 to 12 damage (random).',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-004',
  },
  {
    id: 'W-005-EVOLVED',
    name: 'Null Pocket',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Remove 2 cards from combat. They return to hand next turn.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-005',
  },
  {
    id: 'W-006-EVOLVED',
    name: 'Dimensional Slash',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 8 damage. Shuffle this card into your draw pile.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-006',
  },
  {
    id: 'W-007-EVOLVED',
    name: 'Resonant Echo',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Add a copy of each of the last 2 cards played this combat to your hand.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-007',
  },
  {
    id: 'W-008-EVOLVED',
    name: 'Dimensional Strike',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Flux. A: Deal 10. B: Deal 4 twice. C: Deal 6 and draw 1.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-008',
    fluxStates: {
      A: 'Deal 10.',
      B: 'Deal 4 twice.',
      C: 'Deal 6 and draw 1.',
    },
  },
  {
    id: 'W-009-EVOLVED',
    name: 'Rift Crack',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Deal 5 damage to all enemies. Open 2 random Rifts for 2 turns.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-009',
  },
  {
    id: 'W-010-EVOLVED',
    name: 'Void Command',
    rarity: 'Common',
    type: 'Skill',
    cost: 0,
    description: 'Gain 1 Energy and draw 1 card.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-010',
  },
  {
    id: 'W-011-EVOLVED',
    name: 'Singularity',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Deal 6 to 14 damage (random).',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-011',
  },
  {
    id: 'W-012-EVOLVED',
    name: 'Strobestep',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Gain 8 Block. Reroll all Flux cards in hand.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-012',
  },
  {
    id: 'W-013-EVOLVED',
    name: 'Warped Edge',
    rarity: 'Common',
    type: 'Attack',
    cost: 1,
    description: 'Flux. A: Deal 7. B: Deal 9. C: Deal 8 and apply Weak 1.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-013',
    fluxStates: {
      A: 'Deal 7.',
      B: 'Deal 9.',
      C: 'Deal 8 and apply Weak 1.',
    },
  },
  {
    id: 'W-014-EVOLVED',
    name: 'Unfold Space',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Return 2 random cards from your discard pile to your hand.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-014',
  },
  {
    id: 'W-015-EVOLVED',
    name: 'Quantum Bulwark',
    rarity: 'Common',
    type: 'Skill',
    cost: 1,
    description: 'Flux. A: Gain 7. B: Gain 10. C: Gain 4 and 4 next turn.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-015',
    fluxStates: {
      A: 'Gain 7.',
      B: 'Gain 10.',
      C: 'Gain 4 and 4 next turn.',
    },
  },
  {
    id: 'W-016-EVOLVED',
    name: 'Prime Rift',
    rarity: 'Common',
    type: 'Skill',
    cost: 2,
    description: 'Open a Cost Rift for 3 turns: 2 random cards in your hand cost 0 each turn.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-016',
  },
  {
    id: 'W-017-EVOLVED',
    name: 'Certainty Wave',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'All Flux cards in your hand lock to their highest-value state for this turn.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-017',
  },
  {
    id: 'W-018-EVOLVED',
    name: 'Absolute Horizon',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Flux cards in your hand no longer shift. Gain 2 Block at turn start.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-018',
  },
  {
    id: 'W-019-EVOLVED',
    name: 'Storm Bolt',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 1,
    description: 'Deal 8 to 24 damage (random).',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-019',
  },
  {
    id: 'W-020-EVOLVED',
    name: 'Rift Strider',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Open 3 random Rifts for 3 turns each.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-020',
  },
  {
    id: 'W-021-EVOLVED',
    name: 'Paradox Lance',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 18 damage. 50% chance to take 4 self damage.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-021',
  },
  {
    id: 'W-022-EVOLVED',
    name: 'Chronostop',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Skip the next turn of up to 2 enemies. Exhaust.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-022',
  },
  {
    id: 'W-023-EVOLVED',
    name: 'Hypercube',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Choose 2 Flux cards in your hand. Lock each to a state of your choice for the rest of combat.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-023',
  },
  {
    id: 'W-024-EVOLVED',
    name: 'Multiversal Shield',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Flux. A: Gain 24. B: Gain 12 and Retain. C: Gain 18 and 1 Energy next turn.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-024',
    fluxStates: {
      A: 'Gain 24.',
      B: 'Gain 12 and Retain.',
      C: 'Gain 18 and 1 Energy next turn.',
    },
  },
  {
    id: 'W-025-EVOLVED',
    name: 'Warp Lance',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Flux. A: Deal 22. B: Deal 12 and Vulnerable 3. C: Deal 14 twice.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-025',
    fluxStates: {
      A: 'Deal 22.',
      B: 'Deal 12 and Vulnerable 3.',
      C: 'Deal 14 twice.',
    },
  },
  {
    id: 'W-026-EVOLVED',
    name: 'Reality Reset',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 1,
    description: 'Reroll all Flux cards in hand, draw, and discard. Draw 2 cards.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-026',
  },
  {
    id: 'W-027-EVOLVED',
    name: 'Disorder',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Enemies\' damage is randomized and reduced by 1 per hit.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-027',
  },
  {
    id: 'W-028-EVOLVED',
    name: 'Quasar',
    rarity: 'Uncommon',
    type: 'Attack',
    cost: 2,
    description: 'Deal 10 to 24 damage to all enemies. Take 3 self damage.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-028',
  },
  {
    id: 'W-029-EVOLVED',
    name: 'Event Singularity',
    rarity: 'Uncommon',
    type: 'Power',
    cost: 2,
    description: 'Flux. A: Draw 2 extra. B: Gain 2 Energy. C: Gain 6 Block each turn.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-029',
    fluxStates: {
      A: 'Draw 2 extra.',
      B: 'Gain 2 Energy.',
      C: 'Gain 6 Block each turn.',
    },
  },
  {
    id: 'W-030-EVOLVED',
    name: 'Mirror Legion',
    rarity: 'Uncommon',
    type: 'Skill',
    cost: 2,
    description: 'Add a copy of 3 cards from your hand to your hand. They cost 0 this turn.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-030',
  },
  {
    id: 'W-031-EVOLVED',
    name: 'The Archer\'s Eye',
    rarity: 'Rare',
    type: 'Attack',
    cost: 2,
    description: 'Deal 24 damage to one target. Ignore all evasion and positional effects. Your next 2 Flux cards lock to their current states.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-031',
  },
  {
    id: 'W-032-EVOLVED',
    name: 'Harmonic Choir',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'Whenever a Flux card in your hand shifts state, deal 5 damage to a random enemy and gain 2 Block.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-032',
  },
  {
    id: 'W-033-EVOLVED',
    name: 'The Molten Face of the World',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 55 damage to all enemies. Apply Vulnerable 3 to all. Open 4 random Rifts for 2 turns. Exhaust.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-033',
  },
  {
    id: 'W-034-EVOLVED',
    name: 'Oracle of the Mysteries',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At start of each turn, reveal the top 2 cards. Once per turn, play either for 1 less Energy (min 0).',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-034',
  },
  {
    id: 'W-035-EVOLVED',
    name: 'Multiverse Slash',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 10 damage to target 5 times. Each hit has a 50% chance to deal double damage.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-035',
  },
  {
    id: 'W-036-EVOLVED',
    name: 'Reality Shaper',
    rarity: 'Rare',
    type: 'Power',
    cost: 3,
    description: 'All Rifts you open last three times as long and their effects are tripled.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-036',
  },
  {
    id: 'W-037-EVOLVED',
    name: 'Observer',
    rarity: 'Rare',
    type: 'Skill',
    cost: 2,
    description: 'This turn: all damage dealt and taken is multiplied by 0 or 2 (33/66 in your favor). Exhaust.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-037',
  },
  {
    id: 'W-038-EVOLVED',
    name: 'Chrono Mastery',
    rarity: 'Rare',
    type: 'Skill',
    cost: 3,
    description: 'Replay every card play from your previous 2 turns in order. Exhaust.',
    archetype: 'Chaos Storm',
    factionId: 'WarpRiders',
    basedOn: 'W-038',
  },
  {
    id: 'W-039-EVOLVED',
    name: 'Reality Forge',
    rarity: 'Rare',
    type: 'Power',
    cost: 2,
    description: 'At start of each turn, lock 2 Flux cards in your hand to states of your choice.',
    archetype: 'Precision Phase',
    factionId: 'WarpRiders',
    basedOn: 'W-039',
  },
  {
    id: 'W-040-EVOLVED',
    name: 'Genesis Forge',
    rarity: 'Rare',
    type: 'Attack',
    cost: 3,
    description: 'Deal 30 damage to all enemies. Apply Weak 3, Vulnerable 3, and 5 Burn. Open 2 Genesis Rifts.',
    archetype: 'Rift Architect',
    factionId: 'WarpRiders',
    basedOn: 'W-040',
  },
];

export const WARPRIDERS_CARDS: Card[] = [
  ...WARPRIDERS_BASE_CARDS,
  ...WARPRIDERS_EVOLVED_CARDS,
];
